### ISSUE TITLE
Leg handler can't complete with waypoint jumps

### ISSUE THREAD

**Issue by hiradg** [UoBFlightLab/drone_trees#14]
Leg handler parallel does not complete (tick success) when encountering a jump in mission. The SuccessOnAll policy needs all waypoint transitions to tick success before moving to landing node.

**Comment by arthurrichards77** [comment]
The leg logic needs a bit more thought.  Using the final waypoint as a detection of landing may not be robust, as for example landing may occur because pilot initiates RTL.  Principle should be that tree returns a clear success or failure at the root, thus closing the app cleanly, for any foreseeable mission outcome.  Therefore we can't assume that the final waypoint will always be executed, or that it even is a landing command.

**Comment by arthurrichards77** [comment]
Also note that the current setting of the parallel policy is driven by the need to avoid that annoying lightning bolt symbol in py_trees when rendering it, which caused a crash in my system every time due to lack of unicode support.  I couldn't find a way to disable it, even though py_trees is supposed to detect missing unicode support.
